#!/bin/sh

SUFFIX=""

case $1 in 
	random) SUFFIX=-rand;;
	all)    SUFFIX="";;
	*)
		echo "$ run (random | all) cmd [flags]";
		exit 1;;
esac

shift

test -x $1 || { echo "No executable at '$1'."; exit 2; }

test -d tmp && rm -rf tmp # don't want old files screwing up tests
mkdir tmp

LOG=tmp/units-$$.out

fail() {
   cat $LOG
   exit 1
}

echo -n "Running tests/ against $@:"

touch $LOG

for file in tests/*$SUFFIX.scm
do
   ($@ -q $file 2>&1 | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
done

for file in tests/*$SUFFIX.sh
do
   (sh $file $@ 2>&1 | grep -v SEED | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
done

wait 

grep ERROR $LOG && fail $LOG

rm $LOG

echo " ok"

