#!/bin/sh

## run only the tests that have RANDOM in them

test -d tmp || mkdir tmp || fail "cannot make tmp/"

LOG=tmp/units-$$.out

fail() {
   cat $LOG
   exit 1
}

echo -n "Running tests/ against $@:"

touch $LOG

MAXMEM=1048576 # 1GB
MAXTIME=60
for file in tests/*.scm
do
   grep -q RANDOM $file && (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; $@ -q $file 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
done

for file in tests/*.sh
do
   grep -q RANDOM $file && (ulimit -S -t $MAXTIME; ulimit -S -m $MAXMEM; sh $file $@ 2>&1 | diff $file.ok - >> $LOG || echo "ERROR: $file" >> $LOG; /bin/echo -n " o") &
done

wait 

grep ERROR $LOG && fail $LOG

rm $LOG

echo " ok"

